### ISSUE TITLE
TimeIssue

### ISSUE THREAD

**Issue by leejiho9898** [ksmfou98/Untact-Operation-Command#6]
fullcallendar 에 event.start가 들어갈 때 Date 마지막에 Z가 붙으면서  ex)2021-09-27T09:30:00.000Z
내가 지정한 시간과 실제로 나타나는 시간이 달라지는 문제가 있음

**Comment by ksmfou98** [comment]
![image](https://user-images.githubusercontent.com/64634992/134620673-3b59ba66-6c5e-4ec1-887c-cbfff6e575e9.png)


타임존 이슈인데 Date 객체를 한국시간으로 변환해주는 작업 해줘야됨 사진 참고

**Comment by ksmfou98** [comment]
![image](https://user-images.githubusercontent.com/64634992/134620827-8213b4e2-1759-46db-8a24-96c749dfd02c.png)
 Date 객체는 한국시간보다 9시간 빠름
